class Actions:
    """Enum for loan Actions"""
    LOAN_ORIGINATED=1
    APPROVED_NOT_ACCEPTED=2
    DENIED_BY_INSTITUTION=3
    WITHDRAWN_BY_APPLICANT=4
    CLOSED_FOR_INCOMPLETE=5
    PURCHASED_BY_INSTITUTION=6
    PREAPPROVAL_DENIED=7
    PREAPPROVAL_APPROVED_NOT_ACCEPTED=8